In [1]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold, StratifiedKFold

In [2]:
dataframe = pd.read_csv("diabetes.csv")
dataframe

     preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [4]:
from sklearn.model_selection import KFold, StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

array1 = dataframe.values
X = dataframe.iloc[:, 0:8]
Y = dataframe.iloc[:, 8]

kfold = StratifiedKFold(n_splits=10, random_state=2025, shuffle=True)

model = RandomForestClassifier(n_estimators=200, random_state=20, max_depth=None)

results = cross_val_score(model, X, Y, cv=kfold)
print(results)
print(results.mean())

[0.84415584 0.71428571 0.75324675 0.7012987  0.72727273 0.79220779
 0.71428571 0.74025974 0.78947368 0.77631579]
0.7552802460697198